name: Check

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:

# permissions:
#   contents: read

jobs:
  # TODO: matrix on (py x streamlit) versions
  # matrix:
  #   python-version: [3.8, 3.9, 3.10, 3.11]
  check:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - run: |
          make format
        continue-on-error: true

      - run: |
          make test
