name: Check

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

# permissions:
#   contents: read

jobs:
  check:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
      - run: |
          PYTHON_VER=${{ matrix.python-version }} make deps

      - run: |
          make format
        continue-on-error: true

      - run: |
          make test
