name: Publish to PyPI
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/streamlit-concurrency
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install pypa/build
        run: |
          python3 -m pip install build --user

      - name: Build
        run: |
          python3 -m build --wheel --sdist

      - uses: pypa/gh-action-pypi-publish@release/v1
